### PR TITLE
feat: use gitignore when copying the recipe files

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by tdejager** [comment]
Just tried it on this: https://github.com/prefix-dev/pixi-build-backends/pull/9

And the result are smaller binaries, in comparison the previous ones were like 300mb
image

**Comment by tdejager** [comment]
Yeah actually, it does still seem to include the `.git` itself. The rest is okay. `.git` by itself is not included in the gitignore, is this something to exclude manually?

image

**Comment by wolfv** [comment]
We can add `.hidden(true)` and then that would also be ignored.

**Comment by tdejager** [comment]
Sounds good!

**Comment by tdejager** [comment]
LGTM!:

image

**Pull request merged**
