### PR TITLE
fix: make tests work better cross-platform

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
@pavelzw this has the potential to fix tests on Windows :) – I haven't tried myself, yet, though. I will also write a few end-to-end-tests that we can execute in CI.

**Comment by swarnimarun** [comment]
Will test on my Windows system.

**Comment by wolfv** [comment]
There is a last issue, I think we might want to use `cmd /k /c <test.bat>` ...

**Comment by swarnimarun** [comment]
surprisingly only one of the snapshot test was broken when I tested locally.
<details>
<summary>Diff/patch for the snapshot fix</summary>

```diff
diff --git a/src/recipe/parser.rs b/src/recipe/parser.rs
index 5c43fb9..c301036 100644
--- a/src/recipe/parser.rs
+++ b/src/recipe/parser.rs
@@ -212,7 +212,10 @@ mod tests {
         let recipe = include_str!("../../examples/xtensor/recipe.yaml");
         let recipe = Recipe::from_yaml(recipe, SelectorConfig::default());
         assert!(recipe.is_ok());
+        #[cfg(target_os = "unix")]
         insta::assert_debug_snapshot!(recipe.unwrap());
+        #[cfg(target_os = "windows")]
+        insta::assert_debug_snapshot!("recipe_windows", recipe.unwrap());
     }
 
     #[test]
diff --git a/src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap b/src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
new file mode 100644
index 0000000..da7d880
--- /dev/null
+++ b/src/recipe/snapshots/rattler_build__recipe__parser__tests__recipe_windows.snap
@@ -0,0 +1,336 @@
+---
+source: src/recipe/parser.rs
+assertion_line: 218
+expression: recipe.unwrap()
+---
+Recipe {
+    package: Package {
+        name: PackageName {
+            normalized: None,
+            source: "xtensor",
+        },
+        version: "0.24.6",
+    },
+    source: [
+        Url(
+            UrlSource {
+                url: Url {
+                    scheme: "https",
+                    cannot_be_a_base: false,
+                    username: "",
+                    password: None,
+                    host: Some(
+                        Domain(
+                            "github.com",
+                        ),
+                    ),
+                    port: None,
+                    path: "/xtensor-stack/xtensor/archive/0.24.6.tar.gz",
+                    query: None,
+                    fragment: None,
+                },
+                checksums: [
+                    Sha256(
+                        [
+                            248,
+                            114,
+                            89,
+                            181,
+                            26,
+                            171,
+                            175,
+                            221,
+                            17,
+                            131,
+                            148,
+                            119,
+                            71,
+                            237,
+                            255,
+                            244,
+                            207,
+                            247,
+                            93,
+                            85,
+                            55,
+                            83,
+                            52,
+                            242,
+                            232,
+                            28,
+                            238,
+                            109,
+                            198,
+                            142,
+                            246,
+                            85,
+                        ],
+                    ),
+                ],
+                file_name: None,
+                patches: [],
+                folder: None,
+            },
+        ),
+    ],
+    build: Build {
+        number: 0,
+        string: None,
+        skip: false,
+        script: [
+            "cmake -G \"NMake Makefiles\" -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% %SRC_DIR%\nnmake\nnmake install",
+        ],
+        script_env: ScriptEnv {
+            passthrough: [],
+            env: {},
+            secrets: [],
+        },
+        ignore_run_exports: [],
+        ignore_run_exports_from: [],
+        run_exports: RunExports {
+            noarch: [],
+            strong: [],
+            strong_constrains: [],
+            weak: [],
+            weak_constrains: [],
+        },
+        noarch: NoArchType(
+            None,
+        ),
+        entry_points: [],
+    },
+    requirements: Requirements {
+        build: [
+            Compiler(
+                Compiler {
+                    language: "cxx",
+                },
+            ),
+            Spec(
+                MatchSpec {
+                    name: Some(
+                        PackageName {
+                            normalized: None,
+                            source: "cmake",
+                        },
+                    ),
+                    version: None,
+                    build: None,
+                    build_number: None,
+                    file_name: None,
+                    channel: None,
+                    subdir: None,
+                    namespace: None,
+                    md5: None,
+                    sha256: None,
+                },
+            ),
+        ],
+        host: [
+            Spec(
+                MatchSpec {
+                    name: Some(
+                        PackageName {
+                            normalized: None,
+                            source: "xtl",
+                        },
+                    ),
+                    version: Some(
+                        Group(
+                            And,
+                            [
+                                Range(
+                                    GreaterEquals,
+                                    Version {
+                                        version: [[0], [0], [7]],
+                                        local: [],
+                                    },
+                                ),
+                                Range(
+                                    Less,
+                                    Version {
+                                        version: [[0], [0], [8]],
+                                        local: [],
+                                    },
+                                ),
+                            ],
+                        ),
+                    ),
+                    build: None,
+                    build_number: None,
+                    file_name: None,
+                    channel: None,
+                    subdir: None,
+                    namespace: None,
+                    md5: None,
+                    sha256: None,
+                },
+            ),
+        ],
+        run: [
+            Spec(
+                MatchSpec {
+                    name: Some(
+                        PackageName {
+                            normalized: None,
+                            source: "xtl",
+                        },
+                    ),
+                    version: Some(
+                        Group(
+                            And,
+                            [
+                                Range(
+                                    GreaterEquals,
+                                    Version {
+                                        version: [[0], [0], [7]],
+                                        local: [],
+                                    },
+                                ),
+                                Range(
+                                    Less,
+                                    Version {
+                                        version: [[0], [0], [8]],
+                                        local: [],
+                                    },
+                                ),
+                            ],
+                        ),
+                    ),
+                    build: None,
+                    build_number: None,
+                    file_name: None,
+                    channel: None,
+                    subdir: None,
+                    namespace: None,
+                    md5: None,
+                    sha256: None,
+                },
+            ),
+        ],
+        run_constrained: [
+            Spec(
+                MatchSpec {
+                    name: Some(
+                        PackageName {
+                            normalized: None,
+                            source: "xsimd",
+                        },
+                    ),
+                    version: Some(
+                        Group(
+                            And,
+                            [
+                                Range(
+                                    GreaterEquals,
+                                    Version {
+                                        version: [[0], [8], [0], [3]],
+                                        local: [],
+                                    },
+                                ),
+                                Range(
+                                    Less,
+                                    Version {
+                                        version: [[0], [10]],
+                                        local: [],
+                                    },
+                                ),
+                            ],
+                        ),
+                    ),
+                    build: None,
+                    build_number: None,
+                    file_name: None,
+                    channel: None,
+                    subdir: None,
+                    namespace: None,
+                    md5: None,
+                    sha256: None,
+                },
+            ),
+        ],
+    },
+    test: Test {
+        imports: [],
+        commands: [
+            "if not exist %LIBRARY_PREFIX%\\include\\xtensor\\xarray.hpp (exit 1)",
+            "if not exist %LIBRARY_PREFIX%\\share\\cmake\\xtensor\\xtensorConfig.cmake (exit 1)",
+            "if not exist %LIBRARY_PREFIX%\\share\\cmake\\xtensor\\xtensorConfigVersion.cmake (exit 1)",
+        ],
+        requires: [],
+        source_files: [],
+        files: [],
+    },
+    about: About {
+        homepage: Some(
+            Url {
+                scheme: "https",
+                cannot_be_a_base: false,
+                username: "",
+                password: None,
+                host: Some(
+                    Domain(
+                        "github.com",
+                    ),
+                ),
+                port: None,
+                path: "/xtensor-stack/xtensor",
+                query: None,
+                fragment: None,
+            },
+        ),
+        repository: Some(
+            Url {
+                scheme: "https",
+                cannot_be_a_base: false,
+                username: "",
+                password: None,
+                host: Some(
+                    Domain(
+                        "github.com",
+                    ),
+                ),
+                port: None,
+                path: "/xtensor-stack/xtensor",
+                query: None,
+                fragment: None,
+            },
+        ),
+        documentation: Some(
+            Url {
+                scheme: "https",
+                cannot_be_a_base: false,
+                username: "",
+                password: None,
+                host: Some(
+                    Domain(
+                        "xtensor.readthedocs.io",
+                    ),
+                ),
+                port: None,
+                path: "/",
+                query: None,
+                fragment: None,
+            },
+        ),
+        license: Some(
+            License {
+                original: "BSD-3-Clause",
+                expr: BSD-3-Clause,
+            },
+        ),
+        license_family: None,
+        license_files: [
+            "LICENSE",
+        ],
+        license_url: None,
+        summary: Some(
+            "The C++ tensor algebra library",
+        ),
+        description: Some(
+            "Multi dimensional arrays with broadcasting and lazy computing",
+        ),
+        prelink_message: None,
+    },
+    extra: (),
+}

```
</details>

**Comment by swarnimarun** [comment]
I am not sure why this was breaking, specifically so will test around.

**Comment by pavelzw** [comment]
Just tested my use case with https://github.com/prefix-dev/rattler-build/pull/292/commits/b4f2eb3742e83876648dbb37e2d00b8e05dff903

it works 🤩

**Comment by wolfv** [comment]
I tested with the test that should fail and it did weird things to my terminal though :D

**Pull request merged**
