### PR TITLE
doc: typo of BasicHTTP result in json decode error

### PR DESCRIPTION
**Pull request by TTTPOB**
as title

### CODE REVIEW

**Comment by TTTPOB** [comment]
this deploy docs ci failed is not problem on my side, this is just a doc update.
I've looked into the doc produced by the `generate-cli-docs` command
doc for the `generate-recipe` subcommand disappears from the final doc, even when running the binary with explict feature specification `cargo run --bin generate-cli-docs --features generate-cli-docs,recipe-generation > docs/reference/cli.md`
I am not familiar with `clap-markdown`, so I am not able to fix this.

**Comment by wolfv** [comment]
I'll have a look. Thanks for your PRs @TTTPOB!

**Comment by TTTPOB** [comment]
Sorry, I made a mistake yestoday, branched from the old `main`, so the cli docs do not include `generate-recipes`

**Comment by wolfv** [comment]
Excellent! :)

**Pull request merged**
