### PR TITLE
prepare release 0.31.0

### PR DESCRIPTION
**Pull request by wolfv**
cc @baszalmstra looking at the changes I had to made I was wondering if there should be a constructor for `Channel::from_url` that takes a `ChannelUrl`?

Can you check that the usage of `ChannelUrl` makes sense?

Also I am enabling sharded, because, why not!?

### CODE REVIEW

**Comment by wolfv** [comment]
@hadim anything else you need?! :) I updated rattler.

**Comment by hadim** [comment]
All good thanks!

**Comment by baszalmstra** [comment]
@wolfv Do you think we should always serialize the URL without the trailing slash?

**Comment by baszalmstra** [comment]
https://github.com/baszalmstra/rattler/pull/new/feat/expose_url_without_trailing_slash

**Comment by baszalmstra** [comment]
https://github.com/conda/rattler/pull/948

**Comment by wolfv** [comment]
@baszalmstra works for me. I'll be waiting for one more rattler release then. It'll probably make things more rebuildable as well :)

**Comment by baszalmstra** [comment]
Just created a new release that contains https://github.com/conda/rattler/pull/948

**Pull request merged**
