### PR TITLE
feat: add `load_from_file` jinja function

### PR DESCRIPTION
**Pull request by swarnimarun**
This PR adds load_from_file function that either loads a map from yaml, json, or toml, or otherwise just loads the entire string source from the file itself.

This is supposed to be an experimental feature.

Note: Currently it doesn't check if the path is inside the output_dir. But it shouldn't be a concern as it happens during jinja to yaml build phase which means we can't have cyclic dependency.

Fixes https://github.com/prefix-dev/rattler-build/issues/244

### CODE REVIEW

**Comment by wolfv** [comment]
Other PR is merged :)

**Comment by swarnimarun** [comment]
rebased

**Comment by wolfv** [comment]
Looks good! If you can write some docs on this, the `git` functions and the `--experimental` flag that would be appreciated! :)

**Comment by swarnimarun** [comment]
finally working. :3

**Pull request merged**
