### PR TITLE
fix: replace absolute symlinks from cache with correct version

### LINKED ISSUE #992: various files which are supposedly installed into the package are not visible when testing the package
(continued from https://discord.com/channels/1082332781146800168/1264423283919687722/1265375809015910420)

I am building the package `llvm-spirv` from [my feedstock](https://github.com/ethanc8/chipstar-forge-feedstocks/blob/master/llvm-spirv/recipe.yaml).

now it's failing in testing with:
```
 │ │ + $PREFIX/bin/llvm-spirv -help
 │ │ /tmp/.tmpsuRFVk/conda_build.sh: line 10: $PREFIX/bin/llvm-spirv: No such file or directory
```
but earlier it put `bin/llvm-spirv` into the package:
```
 │ │ Files in package:
 │ │   - bin/llvm-spirv
 │ │   - info/about.json
 │ │   - info/hash_input.json
 │ │   - info/index.json
 │ │   - info/licenses/LICENSE.TXT
 │ │   - info/paths.json
 │ │   - info/recipe/LICENSE.txt
 │ │   - info/recipe/build.sh
 │ │   - info/recipe/build_install.sh
 │ │   - info/recipe/install.sh
 │ │   - info/recipe/recipe.yaml
 │ │   - info/recipe/rendered_recipe.yaml
 │ │   - info/recipe/variant_config.yaml
 │ │   - info/tests/0/run_test.sh
 │ │ Creating target folder "/home/runner/work/chipstar-forge-feedstocks/chipstar-forge-feedstocks/output/linux-64"
 │ │ Compressing archive...
 │ │ Archive written to "/home/runner/work/chipstar-forge-feedstocks/chipstar-forge-feedstocks/output/linux-64/llvm-spirv-17.0.2-h44954ab_0.conda"
```

You can see the full build log at https://github.com/ethanc8/chipstar-forge-feedstocks/actions/runs/10063290370/job/27817743293.

### PR DESCRIPTION
**Pull request by wolfv**
This might fix #992 

I should add a test tomorrow.

### CODE REVIEW

**Comment by ethanc8** [comment]
I have a build here: https://github.com/ethanc8/random-uploads/releases/tag/rattler-build-099961f

**Comment by wolfv** [comment]
I hope so, yes! I'll check right now with your recipe.

**Comment by wolfv** [comment]
@ethanc8 - I think with the last push it should finally work as expected. Will have to add a test for symlinks-in-subfolders :)

**Comment by ethanc8** [comment]
x86_64 Ubuntu 22.04 binary here: https://github.com/ethanc8/random-uploads/releases/tag/rattler-build-21666c8
(maybe I should look into using CI artifacts though)

**Pull request merged**
