### PR TITLE
feat: set environment variables for package tests

### LINKED ISSUE #764: `PKG_VERSION` not set during test
Just saw that this failed 

```
    - test "$(cppcheck --version)" == "Cppcheck $PKG_VERSION"
```

### PR DESCRIPTION
**Pull request by orhun**
fixes #764

will follow up with an example

### CODE REVIEW

**Comment by wolfv** [comment]
this is not going to work for "standalone" tests though (e.g. when runnign with `rattler-build test -p ./mypkg.tar.bz2`).

We need to extract the info either from the filename or from the info.json.

**Comment by orhun** [comment]
> We need to extract the info either from the filename or from the index.json.

`env_vars::vars` currently requires and `Output` to construct the the environment variables.

Is there an easy way (helper function?) of getting an `Output` from a package file? How can we achieve that?

**Comment by wolfv** [comment]
No there is no easy way, but for the few variables we can just make a separate function

- PKG_VERSION
- PKG_NAME
- PKG_BUILD_STRING
- PKG_BUILD_NUMBER

are the ones that come to mind. They are readily available in the `index.json` and we are already parsing that file at teh beginning of the test execution IIRC.

**Comment by orhun** [comment]
Alright that makes sense, will add a function to add the available variables.

**Pull request closed without merging**
