### PR TITLE
expose and store compression level and compression threads

### LINKED ISSUE #376: Support compression level setting for bz2 and zstd
It would be nice to have support for something like `--zstd-compression-level` or `--package-format conda:15`

### PR DESCRIPTION
**Pull request by wolfv**
fixes #376

### CODE REVIEW

**Comment by pavelzw** [comment]
@wolfv is there a reason why `compression_threads` defaults to `1` and not the highest amount?

**Comment by wolfv** [comment]
Not really except that I haven't tested it much yet. But I am fine with changing it to `num_cpu` (although that should be done earlier in the code because we want to store that in the recipe, too). I haven't yet verified that compression threads do not change the SHA256 of the final package

**Comment by wolfv** [comment]
Yeah, we would allow to use a different thread count, but not store it in the recipe. At least that's the idea ...

**Comment by wolfv** [comment]
But if we verify that the thread count doesn't change the result we can also skip storing it.

**Pull request merged**
