### PR TITLE
Format branch/tag refspecs for git-fetch as `<src>:<dst>`

### PR DESCRIPTION
**Pull request by andrewjcg**
This fixes a bug where new branches, added after `src_cache` was originally cloned, wouldn't be able to be successfully checkout out. Fix by using a refspec which creates and destination branch/tag.

### CODE REVIEW

**Comment by wolfv** [comment]
Thanks!

**Comment by wolfv** [comment]
Hey @andrewjcg - the CI is failing. I would be happy to merge if that's fixed :)

**Comment by andrewjcg** [comment]
Sorry for the delay -- I think I got the tests passing now.

**Comment by wolfv** [comment]
No problem, thanks for working on this 🚀

**Pull request merged**
