### PR TITLE
release: 0.20.0

### PR DESCRIPTION
**Pull request by nichmor**

### CODE REVIEW

**Review by baszalmstra — APPROVED** [review]

**Comment by baszalmstra** [comment]
We should really start keeping a changelog!

**Comment by nichmor** [comment]
> We should really start keeping a changelog!

In theory we can generate one from our github release page?

**Comment by baszalmstra** [comment]
Yeah or using git cliff! There is already a cliff file in the repo.

**Comment by nichmor** [comment]
> Yeah or using git cliff! There is already a cliff file in the repo.

Made the issue!

**Pull request merged**
