### PR TITLE
feat: add completions generation for shells

### LINKED ISSUE #366: Add rattler-build shell completion

### PR DESCRIPTION
**Pull request by swarnimarun**
uses clap-complete should support most shells, for support for any other shell an issue would need to be filed to clap

Fixes #366

### CODE REVIEW

**Comment by wolfv** [comment]
Cool! Do you think you can add a little usage section to the docs?

**Comment by swarnimarun** [comment]
Also note: currently haven't added support for nushell and fig. They are separate and require different imports and setup etc.

**Comment by wolfv** [comment]
Looks good to me. Will merge once the windows test is fixed :)

**Comment by wolfv** [comment]
I am rebasing this one .

**Review by wolfv — APPROVED** [review]

**Comment by pavelzw** [comment]
It would be nice to have a bit more consistent experience.

```
❯ pixi --help
A package management and workflow tool

Usage: pixi [OPTIONS] <COMMAND>

Commands:
  completion  Generates a completion script for a shell
```

```
❯ pixi completion --help
Generates a completion script for a shell

Usage: pixi completion [OPTIONS]

Options:
  -s, --shell <SHELL>  The shell to generate a completion script for (defaults to 'bash') [possible values: bash, elvish, fish, powershell,
                       zsh]
  -v, --verbose...     More output per occurrence
  -q, --quiet...       Less output per occurrence
      --color <COLOR>  Whether the log needs to be colored [default: auto] [possible values: always, never, auto]
  -h, --help           Print help
```

Also, it would be nice to change the `tracing::info!` to `tracing::debug!`

Otherwise, we will always have output when putting `eval "$(rattler-build --generate=zsh)"` in your `~/.zshrc`.

**Comment by pavelzw** [comment]
@swarnimarun would you like to take care of this in a follow-up PR?

**Comment by swarnimarun** [comment]
makes sense.

**Pull request merged**
