### PR TITLE
Add support for uploading to anaconda.org

### LINKED ISSUE #440: Implement `upload` command for Anaconda.org
Upload works for quetz, artifactory and prefix.dev but not for anaconda.org yet.

I think originally @travishathaway was interested in this.

### PR DESCRIPTION
**Pull request by 0xbe7a**
- add uploading to anaconda.org
- use shared Package struct
- rename to ExtractedPackage

Closes #440

### CODE REVIEW

**Comment by 0xbe7a** [comment]
Should we add a `--force` option that replaces uploaded files in case of conflicts instead of failing @wolfv ? In conda-forge this is afaik never intended

**Comment by wolfv** [comment]
Awesome! I do think that adding a `--force` option is good, because some people use that for testing. There should be other mechanisms to prevent that in `conda-forge` :)

**Comment by 0xbe7a** [comment]
I have added a `--force` option that deletes existing files in case of conflicts

**Comment by 0xbe7a** [comment]
We should probably add an end-to-end test to upload a test package to anaconda.org and maybe test the --force option as well.

**Comment by wolfv** [comment]
Looks great, and I am very excited about this "feature-completeness"! 

Do you want to add the e2e test in this PR or do you want to make another PR?

**Comment by 0xbe7a** [comment]
I will include it in this PR

**Pull request merged**
