### PR TITLE
feat: support scp-style SSH urls for Git source

### LINKED ISSUE #672: Make sure that `git@github.com:blabla` urls' work in git source
The SSH style URLs don't work because we don't parse them correctly. We might have to introduce a third kind of URL (URL, SSH_URL and Path) when parsign a git source.

### PR DESCRIPTION
**Pull request by orhun**
We now support:

```yml
source:
  git: git@github.com:killercup/cargo-edit.git
```

Todo list:

- [ ] Update documentation about this new key
- [ ] Update one of the examples to use this

closes #672

### CODE REVIEW

**Comment by baszalmstra** [comment]
Nice! We also need to add this to the https://github.com/prefix-dev/recipe-format

**Comment by wolfv** [comment]
I think we don't need to update examples or even docs. But it would be good to use this in one of the end-to-end tests or another test. And the lint needs fixing. Then I am happy to merge!

**Comment by orhun** [comment]
Looks like there is a problem with using SSH URLs in the CI:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by orhun** [comment]
We need to add an SSH key to clone over SSH 💀 

<https://stackoverflow.com/questions/60222741/github-actions-and-git-clone-issue>

**Comment by wolfv** [comment]
Hmm, well, if there is no quick way of testing that it might not matter that much. We could add a test that just makes sure that we can parse these.

**Review by wolfv — APPROVED** [review]

**Pull request merged**
