### PR TITLE
fix: some regressions with pretty-printing and add no-wrap printing

### LINKED ISSUE #1124: ENH: Do not wrap lines in logs (or provide an option to avoid wrapping)
In https://github.com/conda-forge/torchaudio-feedstock/pull/4, I see the following kind of lines
```
 │ │ │ =========================== short test summary info ============================
 │ │ │ FAILED test/torchaudio_unittest/compliance/kaldi/kaldi_compatibility_cpu_test.py::TestKaldiFloat32::test_fbank_00 - KeyError: 'foo\n\nTo execute this tes
 │ │ │ t, run the following from the base repo dir:\n     python test/run/etc/conda/test-files/torchaudio/1/test/torchaudio_unittest/compliance/kaldi/kaldi_comp
 │ │ │ atibility_cpu_test.py -k TestKaldiFloat32.test_fbank_00\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'
 │ │ │ FAILED test/torchaudio_unittest/compliance/kaldi/kaldi_compatibility_cpu_test.py::TestKaldiFloat32::test_fbank_01 - KeyError: 'foo\n\nTo execute this tes
 │ │ │ t, run the following from the base repo dir:\n     python test/run/etc/conda/test-files/torchaudio/1/test/torchaudio_unittest/compliance/kaldi/kaldi_comp
 │ │ │ atibility_cpu_test.py -k TestKaldiFloat32.test_fbank_01\n\nThis message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0'
 │ │ │ FAILED [...]
```

And various other places where long lines get wrapped. This makes the logs very hard to read (compared to having all the test names nicely aligned, for example), so if not the default (my preference), then there should at least be an option to disable line wrapping.

### PR DESCRIPTION
**Pull request by wolfv**
cc @h-vetinari this should stop wrapping lines in CI :)

fixes #1124

### CODE REVIEW

**Comment by wolfv** [comment]
@h-vetinari - it works but only when manually setting the `--no-wrap-lines` - there is a little bug with the automatic CI setting :)

**Comment by wolfv** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1065350&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=7b6f2c87-f3a7-5133-8d84-7c03a75d9dfc

**Comment by h-vetinari** [comment]
Cool thanks! Presumably we need to add `--no-wrap-lines` somewhere in smithy?

**Comment by wolfv** [comment]
yes, that would be one way. Or we fix up the detection of `CI` in rattler-build :)

**Pull request merged**
