### PR TITLE
feat: make binary smaller size

### PR DESCRIPTION
**Pull request by nichmor**
based on suggestions from: 
https://github.com/johnthagen/min-sized-rust
https://arusahni.net/blog/2020/03/optimizing-rust-binary-size.html
and pixi workflow

### CODE REVIEW

**Comment by baszalmstra** [comment]
Nice! Curious about the difference!

**Comment by nichmor** [comment]
> Nice! Curious about the difference!

comparing to latest build from main using these optimisations

we are saving **5.9mb** for x86_64-unknown-linux-musl

**Comment by wolfv** [comment]
That's great!

**Comment by wolfv** [comment]
I think we should only use these on release though, because usually they make the pipeline slower to run, right?

**Comment by nichmor** [comment]
> I think we should only use these on release though, because usually they make the pipeline slower to run, right?

yes! I removed the if-guard to test it on my PR only

**Comment by nichmor** [comment]
> I think we should only use these on release though, because usually they make the pipeline slower to run, right?

I've added back git.ref guard

**Pull request merged**
