### PR TITLE
feat: documentation versioning

### PR DESCRIPTION
**Pull request by swarnimarun**
Sample it at: https://swarnimarun.github.io/rattler-build

Latest(0.7.0): https://swarnimarun.github.io/rattler-build/latest

Dev(master): https://swarnimarun.github.io/rattler-build/dev

This is still draft as I am currently stuck on fixing the CI to actually work with mike which is harder than it looks. 

Also should we setup a gh-pages branch that will reduce the deploy from artifact step. cc: @wolfv 

Note: the current issue with CI setup is getting output to a directory, `mike` the tool mkdocs uses for versioning doesn't support output to a directory, it only supports pushing to a branch.

### CODE REVIEW

**Comment by swarnimarun** [comment]
what the gh-pages branch looks like generated by mike.
https://github.com/swarnimarun/rattler-build/tree/gh-pages

**Comment by wolfv** [comment]
Good stuff :)

**Comment by wolfv** [comment]
> Also should we setup a gh-pages branch that will reduce the deploy from artifact step. cc: @wolfv

I don't think I care as long as it works.

**Comment by swarnimarun** [comment]
Testing the CI on my personal repo is a bit too fiddly, for now take a look and let me know if it looks correct. I have a split the Ci into build, release and dev. For testing, release and master branch docs respectively.

Defaults to latest/newest release.

**Pull request merged**
